version: "3.9"

services:
  web:
    container_name: pinhouse-fe
    build:
      context: .
      dockerfile: Docker-pinhouse-file
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
